### ISSUE TITLE
I tried with Unified Service Desk 4.1, the application is crashing while recording.

### ISSUE THREAD

**Issue by beuaaa** [beuaaa/pywinauto_recorder#11]
[I tried with Unified Service Desk 4.1, the application is crashing while recording.](https://github.com/pywinauto/pywinauto/issues/956#issuecomment-654923081)

**Comment by beuaaa** [comment]
Could you copy/paste here the messages in the console if the console is still here after the crash of pywinauto recorder?

**Comment by jjbright** [comment]
I'll work on this further and share you additional traceback, as I'm busy with pywinauto to automate my complex application.
@beuaaa I did mention that my application (USD 4.1) crashes while trying the recorder.

Here is my environment and software's -
OS : windows 10 64 bit
App :  Unified Service Desk 4.1 for Microsoft Dynamics CRM

This application have WPF components and inbuilt browser (chrome - cefsharp) process, so some of the controls

**Comment by beuaaa** [comment]
@jjbright 
Have you tried again with the latest version (0.3.7). Is the problem fixed?

**Comment by beuaaa** [comment]
Having no news, I take the liberty of closing this issue. Do not hesitate to reopen it if needed.
