### ISSUE TITLE
Application starts and immediately closes

### ISSUE THREAD

**Issue by wgalantino** [beuaaa/pywinauto_recorder#14]
Hey - this seems like an awesome thing to be able to do.
I pip installed and downloaded the windows exe - when I try to open it though I can see the command prompt come up for a second but no application follows like in the video - any ideas on what could cause this?

**Comment by beuaaa** [comment]
It is because of this [issue](https://github.com/beuaaa/pywinauto_recorder/issues/9). I am looking for a solution. Any help is welcome.

**Comment by beuaaa** [comment]
Could you try again and fill this [form](https://docs.google.com/forms/d/e/1FAIpQLSdvxXJCYfoFUaTVHCDzGxkMbc_8qq68pTb_7hPbaPUDyYlOeQ/viewform) please?

**Comment by DenverDaveH** [comment]
Hello,
It appears that I too am seeing this. I have filled out the survey as mentioned above. I should say that Windows security did not like this file. And I told Symantec to ignore it so it could be that. 
I will go into Symantec and add this to the exclusions. And then update.

**Comment by beuaaa** [comment]
Hello @DenverDaveH , I just sent you an email.

**Comment by DenverDaveH** [comment]
Do you have the updated pywintautorecorder.exe on the documentation page? I will download it and see...

**Comment by beuaaa** [comment]
Yes, pywintautorecorder.exe on the documentation page is updated to v0.3.7

**Comment by DenverDaveH** [comment]
And when we had our meeting, should I make sure all applications were closed? And should I get desktop icons to a minimum too? I have this in my head so I want to be sure. 
Or maybe try it on a virtualbox windows blank vm?

**Comment by beuaaa** [comment]
When we had our meeting, I could see that Pywinauto recorder was running slowly.

Pywinauto is slow when there are many GUI elements. The next version will be faster. Pywinauto recorder will benefit from this optimization. 
However, it is never too slow on my laptop except when it is not plugged to the mains and goes into power saving mode.

So if you are using a laptop make sure it is powered. And if it's still too slow, close everything that's not useful.

Let me know if you have made any improvement.

**Comment by beuaaa** [comment]
Having no news, I take the liberty of closing this issue. Do not hesitate to reopen it if needed.
