### ISSUE TITLE
Icons folder is missing causing unability to replay recorded script

### ISSUE THREAD

**Issue by RolandMisica** [beuaaa/pywinauto_recorder#22]
when you install pywinauto_recorder using:
pip install -U pywinauto_recorder

and try to run previously recorded script, this crash occurred:
![error](https://user-images.githubusercontent.com/47061898/111826230-b8d9be00-88e8-11eb-8e3a-666e40215a75.png)

**Comment by beuaaa** [comment]
When you install pywinauto_recorder using:
pip install -U pywinauto_recorder

It does not install the Pywinauto recorder GUI.

Indeed, the icons directory is not in the package. To get it, you have to [download](https://github.com/beuaaa/pywinauto_recorder/archive/refs/heads/master.zip) the whole project which also contains the main GUI of pywinauto recorder.

But it is indeed possible to record a Python script by calling the start_recording() function without going through the GUI.

To fix this bug I will move the Icons directory in the package in the next version of Pywinauto recorder.

**Comment by beuaaa** [comment]
It is fixed on version 0.3.8. Can you retry with this version to confirm it is fixed for you?

**Comment by RolandMisica** [comment]
Hi, I installed the 0.3.8 version via pip, and it didn't help. I had to copy Icons into pywinauto package folder manually. 

Maybe I got the workflow somehow wrong:
1. I downloaded the installer and installed it
2. Recorded script with executable
3. I ran the generated script in my Python venv , where I installed the pywinauto_recorder package via pip.

If the package is not intended to run scripts and it only serves a use for some API stuff, then my bug maybe is not a bug and is not relevant.

**Comment by beuaaa** [comment]
@RolandMisica  The Icons directory should have been moved into the package and it should have worked but I confess I did not test it. In fact, I forgot to commit the Icons directory. I need to take the time to do it properly but I won't be able to do it until next week. 

Your bug is relevant but I think that we should not put the icons in the package because there is no need to display the icons in replay mode.

So I need to make sure that the package can run a script without requiring the icons.

**Comment by beuaaa** [comment]
I just committed and pushed the Icons directory and published another package. It should work now.

**Comment by beuaaa** [comment]
@RolandMisica Can I close this issue?

**Comment by beuaaa** [comment]
@RolandMisica Having no news, I take the liberty of closing this issue. Do not hesitate to reopen it if needed.

**Comment by beuaaa** [comment]
Even in version 3.9.0 the icon directory is still not present in the package but I don't know how to solve this problem for the moment.

**Comment by RolandMisica** [comment]
Hi, sorry for not answering, I was off...
I tested it , varsion 0.3.9 isn't working from me either
....but you managed to fix it in new (0.4.0) version.

So this issue can be closed now
