### ISSUE TITLE
Cannot download pywinauto_recorder.exe from website / cannot run pywinautorecorder.py

### ISSUE THREAD

**Issue by josephbarsness** [beuaaa/pywinauto_recorder#30]
I was hopeful to use this tool to automate some of the more manual tasks that I have as a part of my job.  When I attempted to download the 'pywinauto_recorder.exe' from your website https://pywinauto-recorder.readthedocs.io/en/latest/ either it would download itself over and over on Chrome and Edge or display with a 'failed' download state in firefox.  I then downloaded and attempted to run the 'pywinautorecorder.py' file but received an error when trying to run the file saying that __main__ was not found.  I have attached two screenshots.  Hopefully this correctly conveys my issue.  Please let me know if you need any further information.  

![two](https://user-images.githubusercontent.com/22079531/132585182-dfd5f41a-1c83-4a92-99f7-b2bd97efd43d.jpg)
![one](https://user-images.githubusercontent.com/22079531/132585183-fc3d35df-ba31-4f42-b7c2-808d219ad013.jpg)

**Comment by beuaaa** [comment]
Hi @josephbarsness,


I did not notice any problem with 'pywinauto_recorder.exe', I was able to download, install and run it.

To run the Python code, try:
```powershell
python.exe .\pywinauto_recorder.py
```

**Comment by josephbarsness** [comment]
Thank you @beuaaa for your response and looking into this issue.  Clearly it is user error on my end.

**Comment by Ben-Mack** [comment]
@beuaaa The official exe download link on doc page now return 404, can you recheck please?

**Comment by beuaaa** [comment]
You're right @Ben-Mack , the download link no longer works. 
I need to find a reliable host and update the link.
Can you recommend a free host?

**Comment by Ben-Mack** [comment]
I usually see other repo provide exe file in Release page, in the Assets toggle of each release: https://github.com/beuaaa/pywinauto_recorder/releases

**Comment by beuaaa** [comment]
You're right, it's a good solution. That's what I'll do. I'll get the download link and update it in the documentation. 

I'll do that tomorrow if I can find the time. I'll keep you posted.
