### ISSUE TITLE
Move offset coordinates

### ISSUE THREAD

**Issue by Pegmode** [beuaaa/pywinauto_recorder#33]
I have run into a few cases where an elements center may not be the actual center of the element I wish to click. I suggest extending the move function to have x, y offsets from the element center.

**Comment by Pegmode** [comment]
Can be simply accomplished with pywinauto.mouse

**Comment by beuaaa** [comment]
Hi @Pegmode,

Glad you were able to solve your problem. 

I just want to point out that by default Pywinauto Recorder does not record relative coordinates and therefore it plays back by clicking in the center. But it is possible to activate the "**Process events -> % relative coordinates**" option in the taskbar menu.

**Comment by Pegmode** [comment]
Thanks, I'll keep this in mind for the future.
There was an odd element in something I was interacting with. I needed manual offsets for portability so I went with doing things manually.
