### ISSUE TITLE
How to simplify a path

### ISSUE THREAD

**Issue by batara666** [beuaaa/pywinauto_recorder#34]
current code that are generated by pywinauto_recorder:

```py
with Window(u"WhatsApp||Pane"):
	with Region(u"WhatsApp Desktop||Document->Search or start new chat Search or start new chat Archived Chat list Keep your phone connected WhatsApp connects to your phone to sync messages. To reduce data usage, connect your phone to Wi-Fi.||Group->||Group"):
		left_click(u"Voice call||Button")
```

It is possible to simplify the path below? (or even make it more stateless)

```
Search or start new chat Search or start new chat Archived Chat list Keep your phone connected WhatsApp connects to your phone to sync messages. To reduce data usage, connect your phone to Wi-Fi.
```

Edit:

Anyway, Thanks for the software, this really saves a lot of times

**Comment by beuaaa** [comment]
Hi @batara666,

Glad you found the solution.

You can try:
```python
with Window(u"WhatsApp||Pane"):
	with Region(u"*"):
		left_click(u"Voice call||Button")
```
or simpler:
```python
left_click(u"WhatsApp||Pane->*->Voice call||Button")
```

In version 0.6.0 of Pywinauto Recorder, the support of * is improved. Version 0.6.0 should be available very soon.
There will also be a video tutorial to explain all the possibilities to identify an element with a path.

Do not hesitate to let me know your wishes of evolution.

**Comment by batara666** [comment]
yes sir, I use the * wildcard, thanks for the reply <3
