### ISSUE TITLE
'AtributeError: unique_path_again'  line 989

### ISSUE THREAD

**Issue by luisaoisdead** [beuaaa/pywinauto_recorder#38]
I run the pywinauto_recorder.py, whith no problems.
It says "Your Pywinauto recorder is up to date."
 but when i pass with the mouse over the pywinauto_recorder pop up window, it crash.

**Comment by beuaaa** [comment]
Hi @luisaoisdead,

I am updating the code for version 0.6.0 of Pywinauto Recorder. As not all files are pushed, there might be an inconsistency. I'll let you know when it's ready.

**Comment by luisaoisdead** [comment]
Thanks!!!
great work!!
