### ISSUE TITLE
Which tool did you use to convert your code to .exe file? 

### ISSUE THREAD

**Issue by XinShiOfficial** [beuaaa/pywinauto_recorder#55]
I made some modifications to this code and packed it to .exe file by pyinstaller. But it doesn't work while reporting an error relative to module keyboard .
I wonder if you met this error and which pack tool did you use.
Thank u for your time. @beuaaa

**Comment by beuaaa** [comment]
Hi @XinShiOfficial,
I use NUITKA, all the files to compile Pywinauto Recorder arer in this [folder](https://github.com/beuaaa/pywinauto_recorder/tree/master/bin).
