### ISSUE TITLE
Seems like the author's cloud share link is down, cannot download EXE

### ISSUE THREAD

**Issue by bk111** [beuaaa/pywinauto_recorder#63]
https://beuaaa.synology.me/Pywinauto_recorder_installer.exe    is 404

**Comment by fauzaanu** [comment]
The actual link is 

https://github.com/beuaaa/pywinauto_recorder/releases/download/0.6.7/Pywinauto_recorder_installer.exe

The docs within the repo has the correct link but I believe the updated docs isn't the one currently live on read the docs.

**Comment by bk111** [comment]
> The actual link is
> 
> https://github.com/beuaaa/pywinauto_recorder/releases/download/0.6.7/Pywinauto_recorder_installer.exe
> 
> The docs within the repo has the correct link but I believe the updated docs isn't the one currently live on read the docs.

thanks

**Comment by beuaaa** [comment]
The automatic generation of the documentation no longer worked and the link to download the installer was broken. Now it's been fixed and everything works normally.
