### ISSUE TITLE
press the ctrl + alt +r, it can't record the action

### ISSUE THREAD

**Issue by ghost** [beuaaa/pywinauto_recorder#8]

**Comment by beuaaa** [comment]
Could you describe the problem more precisely?
Is the Record icon displayed?
Do the regions under the mouse cursor turn green?

**Comment by SandipJaiswal** [comment]
Facing same issue. CTL + ALT + R fails to create the recorded .py file.  The various actions on screen do change colors while performing the action during recording.

Using the latest version. Below is the command output.


C:\apps\Record_files\pywinauto_recorder.dist\pywinauto_recorder Traceback (most recent call last):
  File "C:\apps\RECORD~1\PYWINA~1.DIS\pywinauto_recorder\core.py", line 29, in get_wrapper_path
  File "C:\apps\RECORD~1\PYWINA~1.DIS\pywinauto\base_wrapper.py", line 669, in __ne__
  File "C:\apps\RECORD~1\PYWINA~1.DIS\pywinauto\base_wrapper.py", line 662, in __eq__
  File "C:\apps\RECORD~1\PYWINA~1.DIS\pywinauto\uia_element_info.py", line 360,in __eq__
_ctypes.COMError: (-2147220991, 'An event was unable to invoke any of the subscribers', (None, None, None, 0, None))
['Traceback (most recent call last):\n', '  File "C:\\apps\\RECORD~1\\PYWINA~1.DIS\\pywinauto_recorder\\core.py", line 29, in get_wrapper_path\n', '  File "C:\\
apps\\RECORD~1\\PYWINA~1.DIS\\pywinauto\\base_wrapper.py", line 669, in __ne__\n', '  File "C:\\apps\\RECORD~1\\PYWINA~1.DIS\\pywinauto\\base_wrapper.py", line
662, in __eq__\n', '  File "C:\\apps\\RECORD~1\\PYWINA~1.DIS\\pywinauto\\uia_element_info.py", line 360, in __eq__\n', "_ctypes.COMError: (-2147220991, 'An even
t was unable to invoke any of the subscribers', (None, None, None, 0, None))\n", '\nDuring handling of the above exception, another exception occurred:\n\n', 'T
raceback (most recent call last):\n', '  File "C:\\apps\\RECORD~1\\PYWINA~1.DIS\\pywinauto_recorder\\recorder.py", line 798, in run\n', '  File "C:\\apps\\RECOR
D~1\\PYWINA~1.DIS\\pywinauto_recorder\\core.py", line 35, in get_wrapper_path\n', "AttributeError: '_ctypes.COMError' object has no attribute 'message'\n"]
Traceback (most recent call last):  File "C:\apps\RECORD~1\PYWINA~1.DIS\pywinauto_recorder\core.py", line 30, in g
et_wrapper_path AttributeError: 'NoneType' object has no attribute 'window_text'
['Traceback (most recent call last):\n', '  File "C:\\apps\\RECORD~1\\PYWINA~1.DIS\\pywinauto_recorder\\core.py", line 30, in get_wrapper_path\n', "AttributeErr
or: 'NoneType' object has no attribute 'window_text'\n", '\nDuring handling of the above exception, another exception occurred:\n\n', 'Traceback (most recent ca
ll last):\n', '  File "C:\\apps\\RECORD~1\\PYWINA~1.DIS\\pywinauto_recorder\\recorder.py", line 781, in run\n', '  File "C:\\apps\\RECORD~1\\PYWINA~1.DIS\\pywin
auto_recorder\\core.py", line 35, in get_wrapper_path\n', "AttributeError: 'AttributeError' object has no attribute 'message'\n"]
Recording in file: ./recorded Sun Sep 13 04_20_38 2020.pyTraceback (most recent call last):  File "C:\apps\RECORD~1\PYWINA~1.DIS\keyboard\_generic.py", line 22, in invoke_
handlers  File "C:\apps\RECORD~1\PYWINA~1.DIS\pywinauto_recorder\recorder.py", line 718, in __key_on   File "C:\apps\RECORD~1\PYWINA~1.DIS\pywinauto_recorder\recorder.py", line 869,
 in stop_recording  File "C:\apps\RECORD~1\PYWINA~1.DIS\pywinauto_recorder\recorder.py", line 93, in write_in_file TypeError: bad operand type for unary +: 'str'

Let me know if need to check other logs on my system

**Comment by beuaaa** [comment]
Could you try again with Pywinauto_recorder_exe v0.20 and fill this [form](https://docs.google.com/forms/d/e/1FAIpQLSdvxXJCYfoFUaTVHCDzGxkMbc_8qq68pTb_7hPbaPUDyYlOeQ/viewform) please?

**Comment by beuaaa** [comment]
Having no news, I take the liberty of closing this issue. Do not hesitate to reopen it if needed.
